"""initial

Revision ID: 97f0ed28cfbb
Revises: 
Create Date: 2024-01-04 16:32:36.540620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f0ed28cfbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('aprovadores_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('cargo_aprovador', sa.String(), nullable=True),
    sa.Column('login_aprovador', sa.String(), nullable=True),
    sa.Column('perfil_aprovador', sa.String(), nullable=True),
    sa.Column('percentual_peso_aprovador', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aprovadores_cliente_id'), 'aprovadores_cliente', ['id'], unique=False)
    op.create_table('configuracao_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_tipo_limite', sa.Integer(), nullable=True),
    sa.Column('id_limite', sa.Integer(), nullable=True),
    sa.Column('id_input_carteira', sa.Integer(), nullable=True),
    sa.Column('id_conversao', sa.Integer(), nullable=True),
    sa.Column('valor_base_proprietaria', sa.DECIMAL(), nullable=True),
    sa.Column('qtd_dias_validade_analise', sa.Integer(), nullable=True),
    sa.Column('qtd_dias_intervalo_minimo_aprovacoes', sa.Integer(), nullable=True),
    sa.Column('qtd_dias_intervalo_maximo_aprovacoes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_cliente_id'), 'configuracao_cliente', ['id'], unique=False)
    op.create_table('tipos_rating_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('codigo_rating', sa.String(), nullable=True),
    sa.Column('descricao_rating', sa.String(), nullable=True),
    sa.Column('prob_default_inicial', sa.DECIMAL(), nullable=True),
    sa.Column('prob_default_final', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_rating_cliente_id'), 'tipos_rating_cliente', ['id'], unique=False)
    op.create_table('alcadas_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_tipo_rating', sa.Integer(), nullable=True),
    sa.Column('limite_minimo_aprovacao', sa.DECIMAL(), nullable=True),
    sa.Column('limite_maximo_aprovacao', sa.DECIMAL(), nullable=True),
    sa.Column('perfil_aprovador', sa.String(), nullable=True),
    sa.Column('percentual_aprovacao', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_rating'], ['tipos_rating_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alcadas_cliente_id'), 'alcadas_cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alcadas_cliente_id'), table_name='alcadas_cliente')
    op.drop_table('alcadas_cliente')
    op.drop_index(op.f('ix_tipos_rating_cliente_id'), table_name='tipos_rating_cliente')
    op.drop_table('tipos_rating_cliente')
    op.drop_index(op.f('ix_configuracao_cliente_id'), table_name='configuracao_cliente')
    op.drop_table('configuracao_cliente')
    op.drop_index(op.f('ix_aprovadores_cliente_id'), table_name='aprovadores_cliente')
    op.drop_table('aprovadores_cliente')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
